import type { Metadata } from "next";
import Script from "next/script";
import localFont from "next/font/local";

// Global Styles
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";

// Components
import Header from "@/components/layout/header/Header";
import Footer from "@/components/layout/Footer";
import { ReduxProvider } from "@/lib/store/provider";


// 🎨 Custom Font: Gordita
const gordita = localFont({
  src: [
    { path: "../../public/fonts/gordita/Gordita-Regular.woff", weight: "400", style: "normal" },
    { path: "../../public/fonts/gordita/Gordita-Medium.woff", weight: "500", style: "normal" },
    { path: "../../public/fonts/gordita/Gordita-Bold.woff", weight: "700", style: "normal" },
  ],
  variable: "--font-gordita",
});

// 🌐 Metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// 🧩 Root Layout
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={gordita.variable}>
        {/* <ReduxProvider > */}
          <div className="flex flex-col h-screen">
            <Header className="w-full" />
            <main>{children}</main>
            <Footer />
          </div>
        {/* </ReduxProvider> */}
        <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
          crossOrigin="anonymous"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
